// Autogenerated AST node
package org.python.pydev.parser.jython.ast;


public interface enclosingType {
    public static final int LIST = 1;
    public static final int TUPLE = 2;

    public static final String[] enclosingTypeNames = new String[] {
        "<undef>",
        "LIST",
        "TUPLE",
    };
}
