// Autogenerated AST node
package org.python.pydev.parser.jython.ast;


public interface expr_contextType {
    public static final int Pattern = 1;
    public static final int Load = 2;
    public static final int Store = 3;
    public static final int Del = 4;
    public static final int AugLoad = 5;
    public static final int AugStore = 6;
    public static final int Param = 7;
    public static final int Artificial = 8;
    public static final int KwOnlyParam = 9;
    public static final int NamedStore = 10;

    public static final String[] expr_contextTypeNames = new String[] {
        "<undef>",
        "Pattern",
        "Load",
        "Store",
        "Del",
        "AugLoad",
        "AugStore",
        "Param",
        "Artificial",
        "KwOnlyParam",
        "NamedStore",
    };
}
