// Autogenerated AST node
package org.python.pydev.parser.jython.ast;

public interface str_typeType {
    public static final int TripleSingle = 1;
    public static final int TripleDouble = 2;
    public static final int SingleSingle = 3;
    public static final int SingleDouble = 4;

    public static final String[] str_typeTypeNames = new String[] {
            "<undef>",
            "TripleSingle",
            "TripleDouble",
            "SingleSingle",
            "SingleDouble",
    };
}
