########################################################################
#
# File Name:            HTMLHRElement
#
# Documentation:        http://docs.4suite.com/4DOM/HTMLHRElement.html
#

### This file is automatically generated by GenerateHtml.py.
### DO NOT EDIT!

"""
WWW: http://4suite.com/4DOM         e-mail: support@4suite.com

Copyright (c) 2000 Fourthought Inc, USA.   All Rights Reserved.
See  http://4suite.com/COPYRIGHT  for license and copyright information
"""

import string
from xml.dom import Node
from xml.dom.html.HTMLElement import HTMLElement

class HTMLHRElement(HTMLElement):

    def __init__(self, ownerDocument, nodeName="HR"):
        HTMLElement.__init__(self, ownerDocument, nodeName)

    ### Attribute Methods ###

    def _get_align(self):
        return string.capitalize(self.getAttribute("ALIGN"))

    def _set_align(self, value):
        self.setAttribute("ALIGN", value)

    def _get_noShade(self):
        return self.hasAttribute("NOSHADE")

    def _set_noShade(self, value):
        if value:
            self.setAttribute("NOSHADE", "NOSHADE")
        else:
            self.removeAttribute("NOSHADE")

    def _get_size(self):
        return self.getAttribute("SIZE")

    def _set_size(self, value):
        self.setAttribute("SIZE", value)

    def _get_width(self):
        return self.getAttribute("WIDTH")

    def _set_width(self, value):
        self.setAttribute("WIDTH", value)

    ### Attribute Access Mappings ###

    _readComputedAttrs = HTMLElement._readComputedAttrs.copy()
    _readComputedAttrs.update({
        "align" : _get_align,
        "noShade" : _get_noShade,
        "size" : _get_size,
        "width" : _get_width
        })

    _writeComputedAttrs = HTMLElement._writeComputedAttrs.copy()
    _writeComputedAttrs.update({
        "align" : _set_align,
        "noShade" : _set_noShade,
        "size" : _set_size,
        "width" : _set_width
        })

    _readOnlyAttrs = filter(lambda k,m=_writeComputedAttrs: not m.has_key(k),
                     HTMLElement._readOnlyAttrs + _readComputedAttrs.keys())
