/* Generated By:JJTree: Do not edit this line. W:\org.python.pydev.parser\src\org\python\pydev\parser\grammar30\PythonGrammar30TreeConstants.java */

package org.python.pydev.parser.grammar30;

public interface PythonGrammar30TreeConstants
{
  public int JJTFILE_INPUT = 0;
  public int JJTFUNCDEF = 1;
  public int JJTDECORATORS = 2;
  public int JJTBEGIN_DECORATOR = 3;
  public int JJTVOID = 4;
  public int JJTEXTRAARGLIST = 5;
  public int JJTEXTRAKEYWORDLIST = 6;
  public int JJTDEFAULTARG = 7;
  public int JJTTUPLE = 8;
  public int JJTAUG_PLUS = 9;
  public int JJTAUG_MINUS = 10;
  public int JJTAUG_MULTIPLY = 11;
  public int JJTAUG_DIVIDE = 12;
  public int JJTAUG_FLOORDIVIDE = 13;
  public int JJTAUG_MODULO = 14;
  public int JJTAUG_AND = 15;
  public int JJTAUG_OR = 16;
  public int JJTAUG_XOR = 17;
  public int JJTAUG_LSHIFT = 18;
  public int JJTAUG_RSHIFT = 19;
  public int JJTAUG_POWER = 20;
  public int JJTEXPR_STMT = 21;
  public int JJTDEL_STMT = 22;
  public int JJTBEGIN_DEL_STMT = 23;
  public int JJTPASS_STMT = 24;
  public int JJTBREAK_STMT = 25;
  public int JJTCONTINUE_STMT = 26;
  public int JJTRETURN_STMT = 27;
  public int JJTBEGIN_RETURN_STMT = 28;
  public int JJTYIELD_STMT = 29;
  public int JJTYIELD_EXPR = 30;
  public int JJTRAISE_STMT = 31;
  public int JJTIMPORT = 32;
  public int JJTIMPORTFROM = 33;
  public int JJTDOTTED_AS_NAME = 34;
  public int JJTDOTTED_NAME = 35;
  public int JJTIMPORT_AS_NAME = 36;
  public int JJTGLOBAL_STMT = 37;
  public int JJTEXEC_STMT = 38;
  public int JJTASSERT_STMT = 39;
  public int JJTIF_STMT = 40;
  public int JJTBEGIN_IF_STMT = 41;
  public int JJTBEGIN_ELIF_STMT = 42;
  public int JJTWHILE_STMT = 43;
  public int JJTBEGIN_WHILE_STMT = 44;
  public int JJTBEGIN_ELSE_STMT = 45;
  public int JJTFOR_STMT = 46;
  public int JJTBEGIN_FOR_STMT = 47;
  public int JJTBEGIN_FOR_ELSE_STMT = 48;
  public int JJTTRYELSE_STMT = 49;
  public int JJTTRYFINALLY_OUTER_STMT = 50;
  public int JJTTRY_STMT = 51;
  public int JJTTRYFINALLY_STMT = 52;
  public int JJTBEGIN_TRY_STMT = 53;
  public int JJTBEGIN_TRY_ELSE_STMT = 54;
  public int JJTBEGIN_FINALLY_STMT = 55;
  public int JJTEXCEPT_CLAUSE = 56;
  public int JJTBEGIN_EXCEPT_CLAUSE = 57;
  public int JJTWITH_STMT = 58;
  public int JJTWITH_VAR = 59;
  public int JJTSUITE = 60;
  public int JJTOLD_LAMBDEF = 61;
  public int JJTTEST = 62;
  public int JJTIF_EXP = 63;
  public int JJTOR_BOOLEAN = 64;
  public int JJTAND_BOOLEAN = 65;
  public int JJTNOT_1OP = 66;
  public int JJTCOMPARISION = 67;
  public int JJTLESS_CMP = 68;
  public int JJTGREATER_CMP = 69;
  public int JJTEQUAL_CMP = 70;
  public int JJTGREATER_EQUAL_CMP = 71;
  public int JJTLESS_EQUAL_CMP = 72;
  public int JJTNOTEQUAL_CMP = 73;
  public int JJTIN_CMP = 74;
  public int JJTNOT_IN_CMP = 75;
  public int JJTIS_NOT_CMP = 76;
  public int JJTIS_CMP = 77;
  public int JJTOR_2OP = 78;
  public int JJTXOR_2OP = 79;
  public int JJTAND_2OP = 80;
  public int JJTLSHIFT_2OP = 81;
  public int JJTRSHIFT_2OP = 82;
  public int JJTADD_2OP = 83;
  public int JJTSUB_2OP = 84;
  public int JJTMUL_2OP = 85;
  public int JJTDIV_2OP = 86;
  public int JJTFLOORDIV_2OP = 87;
  public int JJTMOD_2OP = 88;
  public int JJTPOS_1OP = 89;
  public int JJTNEG_1OP = 90;
  public int JJTINVERT_1OP = 91;
  public int JJTPOW_2OP = 92;
  public int JJTCALL_OP = 93;
  public int JJTINDEX_OP = 94;
  public int JJTDOT_OP = 95;
  public int JJTLIST = 96;
  public int JJTDICTIONARY = 97;
  public int JJTFALSE = 98;
  public int JJTTRUE = 99;
  public int JJTNONE = 100;
  public int JJTSTRJOIN = 101;
  public int JJTLAMBDEF = 102;
  public int JJTSUBSCRIPTLIST = 103;
  public int JJTELLIPSES = 104;
  public int JJTSLICE = 105;
  public int JJTCOLON = 106;
  public int JJTCOMMA = 107;
  public int JJTLIST_FOR = 108;
  public int JJTDECORATED = 109;
  public int JJTCLASSDEF = 110;
  public int JJTEXTRAARGVALUELIST = 111;
  public int JJTEXTRAKEYWORDVALUELIST = 112;
  public int JJTKEYWORD = 113;
  public int JJTNUM = 114;
  public int JJTCOMPLEX = 115;
  public int JJTNAME = 116;
  public int JJTSTRING = 117;
  public int JJTBINARY = 118;


  public String[] jjtNodeName = {
    "file_input",
    "funcdef",
    "decorators",
    "begin_decorator",
    "void",
    "ExtraArgList",
    "ExtraKeywordList",
    "defaultarg",
    "tuple",
    "aug_plus",
    "aug_minus",
    "aug_multiply",
    "aug_divide",
    "aug_floordivide",
    "aug_modulo",
    "aug_and",
    "aug_or",
    "aug_xor",
    "aug_lshift",
    "aug_rshift",
    "aug_power",
    "expr_stmt",
    "del_stmt",
    "begin_del_stmt",
    "pass_stmt",
    "break_stmt",
    "continue_stmt",
    "return_stmt",
    "begin_return_stmt",
    "yield_stmt",
    "yield_expr",
    "raise_stmt",
    "Import",
    "ImportFrom",
    "dotted_as_name",
    "dotted_name",
    "import_as_name",
    "global_stmt",
    "exec_stmt",
    "assert_stmt",
    "if_stmt",
    "begin_if_stmt",
    "begin_elif_stmt",
    "while_stmt",
    "begin_while_stmt",
    "begin_else_stmt",
    "for_stmt",
    "begin_for_stmt",
    "begin_for_else_stmt",
    "tryelse_stmt",
    "tryfinally_outer_stmt",
    "try_stmt",
    "tryfinally_stmt",
    "begin_try_stmt",
    "begin_try_else_stmt",
    "begin_finally_stmt",
    "except_clause",
    "begin_except_clause",
    "with_stmt",
    "with_var",
    "suite",
    "old_lambdef",
    "test",
    "if_exp",
    "or_boolean",
    "and_boolean",
    "not_1op",
    "comparision",
    "less_cmp",
    "greater_cmp",
    "equal_cmp",
    "greater_equal_cmp",
    "less_equal_cmp",
    "notequal_cmp",
    "in_cmp",
    "not_in_cmp",
    "is_not_cmp",
    "is_cmp",
    "or_2op",
    "xor_2op",
    "and_2op",
    "lshift_2op",
    "rshift_2op",
    "add_2op",
    "sub_2op",
    "mul_2op",
    "div_2op",
    "floordiv_2op",
    "mod_2op",
    "pos_1op",
    "neg_1op",
    "invert_1op",
    "pow_2op",
    "Call_Op",
    "Index_Op",
    "Dot_Op",
    "list",
    "dictionary",
    "False",
    "True",
    "None",
    "strjoin",
    "lambdef",
    "subscriptlist",
    "Ellipses",
    "Slice",
    "Colon",
    "Comma",
    "list_for",
    "decorated",
    "classdef",
    "ExtraArgValueList",
    "ExtraKeywordValueList",
    "Keyword",
    "Num",
    "Complex",
    "Name",
    "String",
    "Binary",
  };
}
