/* Generated By:JJTree&JavaCC: Do not edit this line. FStringsGrammarConstants.java */
package org.python.pydev.parser.grammar_fstrings;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FStringsGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int LBRACE = 7;
  /** RegularExpression Id. */
  int RBRACE = 8;
  /** RegularExpression Id. */
  int LBRACKET = 9;
  /** RegularExpression Id. */
  int RBRACKET = 10;
  /** RegularExpression Id. */
  int EXCLAMATION = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int QUOTE = 13;
  /** RegularExpression Id. */
  int QUOTE2 = 14;
  /** RegularExpression Id. */
  int BACKSLASH = 15;
  /** RegularExpression Id. */
  int TEXT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\":\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\\\"",
    "<TEXT>",
  };

}
