/* Generated By:JJTree: Do not edit this line. D:\eclipse_workspace\org.python.pydev.parser\src\org\python\parser\PythonGrammarTreeConstants.java */

package org.python.parser;

public interface PythonGrammarTreeConstants
{
  public int JJTSINGLE_INPUT = 0;
  public int JJTFILE_INPUT = 1;
  public int JJTEVAL_INPUT = 2;
  public int JJTFUNCDEF = 3;
  public int JJTDECORATORS = 4;
  public int JJTVOID = 5;
  public int JJTEXTRAARGLIST = 6;
  public int JJTEXTRAKEYWORDLIST = 7;
  public int JJTDEFAULTARG = 8;
  public int JJTTUPLE = 9;
  public int JJTAUG_PLUS = 10;
  public int JJTAUG_MINUS = 11;
  public int JJTAUG_MULTIPLY = 12;
  public int JJTAUG_DIVIDE = 13;
  public int JJTAUG_FLOORDIVIDE = 14;
  public int JJTAUG_MODULO = 15;
  public int JJTAUG_AND = 16;
  public int JJTAUG_OR = 17;
  public int JJTAUG_XOR = 18;
  public int JJTAUG_LSHIFT = 19;
  public int JJTAUG_RSHIFT = 20;
  public int JJTAUG_POWER = 21;
  public int JJTEXPR_STMT = 22;
  public int JJTPRINTEXT_STMT = 23;
  public int JJTPRINT_STMT = 24;
  public int JJTDEL_STMT = 25;
  public int JJTPASS_STMT = 26;
  public int JJTBREAK_STMT = 27;
  public int JJTCONTINUE_STMT = 28;
  public int JJTRETURN_STMT = 29;
  public int JJTYIELD_STMT = 30;
  public int JJTRAISE_STMT = 31;
  public int JJTIMPORT = 32;
  public int JJTIMPORTFROM = 33;
  public int JJTDOTTED_AS_NAME = 34;
  public int JJTDOTTED_NAME = 35;
  public int JJTIMPORT_AS_NAME = 36;
  public int JJTGLOBAL_STMT = 37;
  public int JJTEXEC_STMT = 38;
  public int JJTASSERT_STMT = 39;
  public int JJTIF_STMT = 40;
  public int JJTIF_BEG_STMT = 41;
  public int JJTELIF_BEG_STMT = 42;
  public int JJTWHILE_STMT = 43;
  public int JJTBEGIN_WHILE_STMT = 44;
  public int JJTFOR_STMT = 45;
  public int JJTTRY_STMT = 46;
  public int JJTTRYFINALLY_STMT = 47;
  public int JJTTRY_BEG_STMT = 48;
  public int JJTTRY_ELSE_STMT = 49;
  public int JJTEXCEPT_CLAUSE = 50;
  public int JJTSUITE = 51;
  public int JJTOR_BOOLEAN = 52;
  public int JJTAND_BOOLEAN = 53;
  public int JJTNOT_1OP = 54;
  public int JJTCOMPARISION = 55;
  public int JJTLESS_CMP = 56;
  public int JJTGREATER_CMP = 57;
  public int JJTEQUAL_CMP = 58;
  public int JJTGREATER_EQUAL_CMP = 59;
  public int JJTLESS_EQUAL_CMP = 60;
  public int JJTNOTEQUAL_CMP = 61;
  public int JJTIN_CMP = 62;
  public int JJTNOT_IN_CMP = 63;
  public int JJTIS_NOT_CMP = 64;
  public int JJTIS_CMP = 65;
  public int JJTOR_2OP = 66;
  public int JJTXOR_2OP = 67;
  public int JJTAND_2OP = 68;
  public int JJTLSHIFT_2OP = 69;
  public int JJTRSHIFT_2OP = 70;
  public int JJTADD_2OP = 71;
  public int JJTSUB_2OP = 72;
  public int JJTMUL_2OP = 73;
  public int JJTDIV_2OP = 74;
  public int JJTFLOORDIV_2OP = 75;
  public int JJTMOD_2OP = 76;
  public int JJTPOS_1OP = 77;
  public int JJTNEG_1OP = 78;
  public int JJTINVERT_1OP = 79;
  public int JJTPOW_2OP = 80;
  public int JJTCALL_OP = 81;
  public int JJTINDEX_OP = 82;
  public int JJTDOT_OP = 83;
  public int JJTLIST = 84;
  public int JJTDICTIONARY = 85;
  public int JJTSTR_1OP = 86;
  public int JJTSTRJOIN = 87;
  public int JJTLAMBDEF = 88;
  public int JJTSUBSCRIPTLIST = 89;
  public int JJTELLIPSES = 90;
  public int JJTSLICE = 91;
  public int JJTCOLON = 92;
  public int JJTCOMMA = 93;
  public int JJTLIST_FOR = 94;
  public int JJTCLASSDEF = 95;
  public int JJTEXTRAARGVALUELIST = 96;
  public int JJTEXTRAKEYWORDVALUELIST = 97;
  public int JJTKEYWORD = 98;
  public int JJTNUM = 99;
  public int JJTCOMPLEX = 100;
  public int JJTNAME = 101;
  public int JJTSTRING = 102;
  public int JJTUNICODE = 103;


  public String[] jjtNodeName = {
    "single_input",
    "file_input",
    "eval_input",
    "funcdef",
    "decorators",
    "void",
    "ExtraArgList",
    "ExtraKeywordList",
    "defaultarg",
    "tuple",
    "aug_plus",
    "aug_minus",
    "aug_multiply",
    "aug_divide",
    "aug_floordivide",
    "aug_modulo",
    "aug_and",
    "aug_or",
    "aug_xor",
    "aug_lshift",
    "aug_rshift",
    "aug_power",
    "expr_stmt",
    "printext_stmt",
    "print_stmt",
    "del_stmt",
    "pass_stmt",
    "break_stmt",
    "continue_stmt",
    "return_stmt",
    "yield_stmt",
    "raise_stmt",
    "Import",
    "ImportFrom",
    "dotted_as_name",
    "dotted_name",
    "import_as_name",
    "global_stmt",
    "exec_stmt",
    "assert_stmt",
    "if_stmt",
    "if_beg_stmt",
    "elif_beg_stmt",
    "while_stmt",
    "begin_while_stmt",
    "for_stmt",
    "try_stmt",
    "tryfinally_stmt",
    "try_beg_stmt",
    "try_else_stmt",
    "except_clause",
    "suite",
    "or_boolean",
    "and_boolean",
    "not_1op",
    "comparision",
    "less_cmp",
    "greater_cmp",
    "equal_cmp",
    "greater_equal_cmp",
    "less_equal_cmp",
    "notequal_cmp",
    "in_cmp",
    "not_in_cmp",
    "is_not_cmp",
    "is_cmp",
    "or_2op",
    "xor_2op",
    "and_2op",
    "lshift_2op",
    "rshift_2op",
    "add_2op",
    "sub_2op",
    "mul_2op",
    "div_2op",
    "floordiv_2op",
    "mod_2op",
    "pos_1op",
    "neg_1op",
    "invert_1op",
    "pow_2op",
    "Call_Op",
    "Index_Op",
    "Dot_Op",
    "list",
    "dictionary",
    "str_1op",
    "strjoin",
    "lambdef",
    "subscriptlist",
    "Ellipses",
    "Slice",
    "Colon",
    "Comma",
    "list_for",
    "classdef",
    "ExtraArgValueList",
    "ExtraKeywordValueList",
    "Keyword",
    "Num",
    "Complex",
    "Name",
    "String",
    "Unicode",
  };
}
