print("foo")
print("foo", end=' ')
print("foo")
print("foo")
print(("foo", test("bla")))
fileobj = open('log', 'a')
print("foo", file=fileobj)
print(file=fileobj)
fileobj.close()
remove('log')

##r

print("foo")
print("foo", end=' ')
print("foo")
print("foo")
print(("foo", test("bla")))
fileobj = open('log', 'a')
print("foo", file=fileobj)
print(file=fileobj)
fileobj.close()
remove('log')
